[programs.localnet]
bucket_program = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/sanny/.config/solana/devnet.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"

[[test.genesis]]
address = "CRATwLpu6YZEeiVq9ajjxs61wPQ9f29s1UoQR9siJCRs"
program = "./tests/programs/crate_token.so"

[[test.genesis]]
address = "1NKyU3qShZC3oJgvCCftAHDi5TFxcJwfyUz2FeZsiwE"
program = "./tests/programs/crate_redeem_in_kind.so"
