[programs.localnet]
bucket_program = "HHqKhZs3ReukRtGqCrj1DJoSknWuCddQ3oyuQY5Uhf5P"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "./tests/bucket_dao.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"

[[test.genesis]]
address = "CRATwLpu6YZEeiVq9ajjxs61wPQ9f29s1UoQR9siJCRs"
program = "./tests/programs/crate_token.so"