[programs.localnet]
bucket_program = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/dennis/.config/solana/anchor-localhost.json"

[scripts]
test = "yarn mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
